package com.pradeephv.jpa.models;
import jakarta.persistence.*;
import lombok.*;
import java.time.LocalDateTime;
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Data
@Table(name = "AUTHOR_TBL")
@Entity
public class Author {

    @Id
    @GeneratedValue
    // (strategy = GenerationType.SEQUENCE,
// generator = "author_sequence"
// )
// //to create out own sequence
// @SequenceGenerator(
// name = "author_sequence",
// sequenceName = "author_sequence",
// allocationSize = 2
// )

    private Integer id;

    @Column(name = "f_name", length = 35)
    private String firstName;

    private String lastName;

    @Column(unique = true, nullable = false)
    private String email;

    private int age;

    @Column(updatable = false, nullable = false)
    private LocalDateTime createdAt;

    @Column(insertable = false)
    private LocalDateTime lastModified;

    // Getters and setters are generated by Lombok @Data
}
