package com.pradeephv.jpa.models;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.time.LocalDateTime;
import java.util.List;


@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
@Data
@Table(name = "AUTHOR_TBL")
@Entity
@NamedQuery(
        name = "Author.findByNamedQuery",
        query = "SELECT a FROM Author a LEFT JOIN FETCH a.courses WHERE a.age >= :age"
)
public class Author extends BaseEntity {


    @Column(name = "f_name", length = 35)
    private String firstName;

    private String lastName;

    @Column(unique = true, nullable = false)
    private String email;

    private int age;

    @Column(updatable = false, nullable = true)
    private LocalDateTime createdAt;

    @Column(insertable = false)
    private LocalDateTime lastModified;

    // Getters and setters are generated by Lombok @Data
    @ManyToMany(mappedBy = "authors", fetch = FetchType.LAZY)
    private List<Course> courses;
}
